### Check if the api works
GET http://localhost:3000/api/ HTTP/1.1
Content-Type: application/json


### Post to sensor
POST http://localhost:3000/api/sensor HTTP/1.1
Content-Type: application/json

{
  "name": "sensor1",
  "value": "10"
}

### Post to sensores

POST http://localhost:3000/api/sensores HTTP/1.1
Content-Type: application/json

## All fields are required
{
    "device": "sensor_test",
    "data" : {
        "sensor1": "test",
        "sensor2": "test"
    },
    "time": "test",
    "WiFi": "test",
    "LoRa": "test",
    "LoRaSNR": "test",
    "packetSize": "test"
}
